version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  video-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-scheduler
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    depends_on:
      - redis
    command: python3 services/video_scheduler/worker.py
